name: desk-quotes-deploy-template

on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string
      runProvisioning:
        required: true
        type: boolean

env:
  DOTNET_VERSION_10: "10.0.x"
  RESOURCE_GROUP_NAME: desk-quotes-rg
  RESOURCE_LOCK_NAME: desk-quotes-rg-delete-lock
  # metadata will be stored, and not where the resource groups will be deployed.
  # You can specify any location for `SUB_DEPLOYMENT_REGION`. It's the region where 
  # the deployment metadata will be stored, and not where the resource groups will be deployed.
  SUB_DEPLOYMENT_REGION: centralindia

jobs:
  provision:
    runs-on: ubuntu-24.04
    environment: ${{ inputs.environmentName }}
    timeout-minutes: 30
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1
      - name: azure login
        uses: azure/login@v2.2.0
        with:
          creds: ${{ secrets.SERVICEPRINCIPAL }}
      # temporarily use az cli to upgrade bicep
      # Context: https://github.com/Azure/bicep/issues/16681#issuecomment-2747568200
      - name: upgrade bicep
        uses: azure/CLI@v2.2.0
        with:
          inlineScript: az bicep upgrade
      #
      # section #1: provisioning the resources on Azure using bicep templates
      #
      # The first step is to create the resource group: `desk-quotes-rg`.
      # The below step can also be manually executed as follows:
      # az deployment sub create --location {LOCATION} --template-file .\createResourceGroup.bicep
      # Note: You can specify any location for `{LOCATION}`. It's the region where the deployment metadata will be stored, and not
      # where the resource groups will be deployed.
      # @TODO: The 'azure/arm-deploy' action will soon be deprecated. Move to the 'azure/bicep-deploy' github action.
      - name: create resource group
        uses: Azure/arm-deploy@v2
        if: ${{ inputs.runProvisioning == true }}
        with:
          scope: subscription
          region: ${{ env.SUB_DEPLOYMENT_REGION }}
          template: ./infra/createResourceGroup.bicep
          parameters: rgName=${{ env.RESOURCE_GROUP_NAME }} envName=${{ inputs.environmentName }} githubCommitSha=${{ github.sha }} githubWorkflowRunId=${{ github.run_id }} githubRef=${{ github.ref }}

  build-deploy-desk-quotes-app:
    runs-on: windows-2025-vs2026
    environment: ${{ inputs.environmentName }}
    timeout-minutes: 10
    needs: provision
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1
      - name: setup dotnet
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION_10 }}
      - name: dotnet restore
        run: dotnet restore
        working-directory: ./src/DeskQuotes
      - name: run unit tests
        run: dotnet test ./tests/DeskQuotes.UnitTests/DeskQuotes.UnitTests.csproj --logger trx --results-directory ./tests/DeskQuotes.UnitTests/TestResults-${{ github.run_id }}-${{ github.run_attempt }}
      - name: publish unit test results
        uses: actions/upload-artifact@v4.3.1
        with:
          name: DeskQuotes.UnitTests
          path: ./tests/DeskQuotes.UnitTests/TestResults-${{ github.run_id }}-${{ github.run_attempt }}
      - name: build desk-quotes app
        run: dotnet publish ./src/DeskQuotes/DeskQuotes.csproj -c Release -o ./Publish/DeskQuotes
      - name: build desk-quotes MSI installer
        run: dotnet publish ./src/DeskQuotes.MSI/DeskQuotes.MSI.wixproj -c Release -o ./Publish/DeskQuotes.MSI
