name: desk-quotes-deploy-template

on:
  workflow_call:

env:
  DOTNET_VERSION_10: "10.0.x"

jobs:
  build-deploy-desk-quotes-app:
    runs-on: windows-2025-vs2026
    timeout-minutes: 10
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1
      - name: setup dotnet
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION_10 }}
      - name: dotnet restore
        run: dotnet restore
        working-directory: ./src/DeskQuotes
      - name: run unit tests
        run: dotnet test ./tests/DeskQuotes.UnitTests/DeskQuotes.UnitTests.csproj --logger trx --results-directory ./tests/DeskQuotes.UnitTests/TestResults-${{ github.run_id }}-${{ github.run_attempt }}
      - name: publish unit test results
        uses: actions/upload-artifact@v4.3.1
        with:
          name: DeskQuotes.UnitTests
          path: ./tests/DeskQuotes.UnitTests/TestResults-${{ github.run_id }}-${{ github.run_attempt }}
      - name: build desk-quotes app
        run: dotnet publish ./src/DeskQuotes/DeskQuotes.csproj -c Release -o ./Publish/DeskQuotes
      - name: build desk-quotes MSI installer
        run: dotnet publish ./src/DeskQuotes.MSI/DeskQuotes.MSI.wixproj -c Release -o ./Publish/DeskQuotes.MSI
